version: '3.9'

services:
    mongodb:
        image: mongo:latest
        container_name: linker-mongodb
        restart: always
        ports:
            - "27018:27017"
        volumes:
            -   "mongodb_data:/data/mongodb"

    linker:
        image: sleeps17/linker:latest
        container_name: linker-service
        restart: always
        ports:
            - "4404:4404"
        depends_on:
            -   mongodb
volumes:
    mongodb_data: {}
