version: '3.9'

services:
    postgres:
        image: postgres:latest
        container_name: linker-postgres
        restart: always
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_USER=sleeps17
            - POSTGRES_DB=linker-db
            - POSTGRES_PASSWORD=Pavel19122004
        networks:
            - proxynet
        volumes:
            - "postgres_data:/data/postgres"

    linker:
        build: .
        container_name: linker-service
        restart: always
        ports:
            - "4404:4404"
        networks:
            - proxynet
        depends_on:
            - postgres

networks:
    proxynet:
        external:
            name: proxynet

volumes:
    postgres_data: {}
