version: '3.9'

services:
    postgres:
        image: postgres:latest
        container_name: linker-postgres
        restart: always
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_USER=sleeps17
            - POSTGRES_DB=linker-db
            - POSTGRES_PASSWORD=Pavel19122004
        volumes:
            -   "postgres_data:/data/postgres"

#    mongodb:
#        image: mongo:latest
#        container_name: linker-mongodb
#        restart: always
#        ports:
#            - "27018:27017"
#        volumes:
#            -   "mongodb_data:/data/mongodb"

    linker:
        image: sleeps17/linker:latest
        container_name: linker-service
        restart: always
        ports:
            - "4404:4404"
        depends_on:
            -   postgres
volumes:
#    mongodb_data: {}
    postgres_data: {}
