version: '3'

tasks:
  build:
    cmds:
      - ./create-network.sh
      - docker-compose build
  up:
    cmds:
      - ./create-network.sh
      - docker-compose up -d
  down:
    cmds:
      - docker-compose down
  test:
    cmds:
      - ./create-network.sh
      - docker-compose up -d postgres
      - sleep 5
      - go test -count=1 ./tests
      - docker-compose down