env: "local"
rest:
    port: ":8080"
    timeout: 10s
grpc:
  port: ":4404"
  timeout: 10s
bot:
  token: "7399117684:AAFZyMnDDg8IDafP6A-vKSIQf0vJOu9psOA"
  update_timeout: 10s
  request_timeout: 10s
data_base:
  host: "{{LinkerDBHost}}"
  port: "{{LinkerDBPort}}"
  name: "{{LinkerDBName}}"
  username: "{{LinkerDBUsername}}"
  password: "{{LinkerDBPassword}}"
  timeout: 10s
url_shortener_client:
  host: "url-shortener-service"
  port: "8081"
