env: "test"
server:
  port: 4404
  timeout: 10s
data_base:
  host: "0.0.0.0"
  port: "5433"
  name: "linker-db"
  username: "sleeps17"
  password: "Pavel19122004"
  timeout: 10s
url_shortener_client:
  host: "url-shortener-service"
  port: "8081"
